### ISSUE TITLE
Out-of-memory bug on enclave after 2 hours (with blocks 1 per sec, rollups 1 per 2 secs)

### ISSUE THREAD

**Issue by joeldudley** [obscuronet/go-obscuro#159]
After running a network of 2x Geth nodes, 2x hosts, 2x enclave services in Azure for c. 2 hours, with one block per second and a rollup every two seconds, the enclave service failed with the OOM below.

To fix this, we need to store stuff to disk which is currently stored in memory.

```
1653055994565 INFO: >   Agg2: Round winner height: 4154
runtime: out of memory: cannot allocate 4194304-byte block (66486272 in use)
fatal error: out of memory

goroutine 24867 [running]:
runtime.throw({0x7fc041d4bce9?, 0x0?})
	/opt/ego/go/src/runtime/panic.go:992 +0x71 fp=0x7fc0580f7280 sp=0x7fc0580f7250 pc=0x7fc041685eb1
runtime.(*mcache).allocLarge(0x7fc058398d00?, 0x178608, 0x0)
	/opt/ego/go/src/runtime/mcache.go:215 +0x1d9 fp=0x7fc0580f72d0 sp=0x7fc0580f7280 pc=0x7fc0416676b9
runtime.mallocgc(0x178608, 0x7fc041f182e0, 0x1)
	/opt/ego/go/src/runtime/malloc.go:1101 +0x5a5 fp=0x7fc0580f7348 sp=0x7fc0580f72d0 pc=0x7fc04165d945
runtime.makeslice(0x7fc04172dd67?, 0x7fc05922ed70?, 0x7fc058914c48?)
	/opt/ego/go/src/runtime/slice.go:103 +0x52 fp=0x7fc0580f7370 sp=0x7fc0580f7348 pc=0x7fc04169d772
github.com/ethereum/go-ethereum/ethdb/memorydb.(*Database).NewIterator(0x7fc05806cc60, {0x7fc05922ed70, 0xa, 0x10}, {0x0, 0x0, 0x7fc0424a0c01?})
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/ethdb/memorydb/memorydb.go:143 +0x205 fp=0x7fc0580f7528 sp=0x7fc0580f7370 pc=0x7fc0419321c5
github.com/ethereum/go-ethereum/core/rawdb.(*nofreezedb).NewIterator(0x7fc0588dd280?, {0x7fc05922ed70?, 0x0?, 0x7fc04171eb80?}, {0x0?, 0x7fc0580f7588?, 0x7fc0580f7608?})
	<autogenerated>:1 +0x34 fp=0x7fc0580f7570 sp=0x7fc0580f7528 pc=0x7fc04194cc94
github.com/obscuronet/obscuro-playground/go/obscuronode/enclave/rawdb.ReadAllHashes({0x7fc055e4a5a8, 0x7fc05803b4b0}, 0x2?)
	/obscuro-playground/go/obscuronode/enclave/rawdb/accessors_chain.go:144 +0x11d fp=0x7fc0580f7698 sp=0x7fc0580f7570 pc=0x7fc0419c3f3d
github.com/obscuronet/obscuro-playground/go/obscuronode/enclave/rawdb.ReadRollupsForHeight({0x7fc04204cef0?, 0x7fc05803b4b0}, 0x7fc05811bcd0?)
	/obscuro-playground/go/obscuronode/enclave/rawdb/accessors_chain.go:130 +0x67 fp=0x7fc0580f7730 sp=0x7fc0580f7698 pc=0x7fc0419c3d07
github.com/obscuronet/obscuro-playground/go/obscuronode/enclave/db.(*storageImpl).FetchRollups(0x103a?, 0x7fc041d53e37?)
	/obscuro-playground/go/obscuronode/enclave/db/storage.go:69 +0x2a fp=0x7fc0580f7758 sp=0x7fc0580f7730 pc=0x7fc0419c50ea
github.com/obscuronet/obscuro-playground/go/obscuronode/enclave.(*enclaveImpl).RoundWinner(0x7fc058234bb0, {0xd9, 0x5c, 0x68, 0x71, 0x67, 0x4f, 0x49, 0x8e, 0xc8, ...})
	/obscuro-playground/go/obscuronode/enclave/enclave.go:270 +0xfd fp=0x7fc0580f79e0 sp=0x7fc0580f7758 pc=0x7fc041d1dd9d
github.com/obscuronet/obscuro-playground/go/obscuronode/enclave.(*server).RoundWinner(0x7fc05806cc20?, {0x7fc0581cbf00?, 0x7fc04176cf06?}, 0x7fc0582bb1e0?)
	/obscuro-playground/go/obscuronode/enclave/server.go:152 +0xc6 fp=0x7fc0580f7ab0 sp=0x7fc0580f79e0 pc=0x7fc041d233e6
github.com/obscuronet/obscuro-playground/go/obscuronode/nodecommon/rpc/generated._EnclaveProto_RoundWinner_Handler({0x7fc042010ee0?, 0x7fc05806cc20}, {0x7fc0420481d0, 0x7fc058938d80}, 0x7fc0584c00c0, 0x0)
	/obscuro-playground/go/obscuronode/nodecommon/rpc/generated/enclave_grpc.pb.go:561 +0x170 fp=0x7fc0580f7b08 sp=0x7fc0580f7ab0 pc=0x7fc041d18e30
google.golang.org/grpc.(*Server).processUnaryRPC(0x7fc058239500, {0x7fc04204b2f0, 0x7fc058135520}, 0x7fc05827b320, 0x7fc0582b8960, 0x7fc042496cd8, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf fp=0x7fc0580f7e48 sp=0x7fc0580f7b08 pc=0x7fc041cfda4f
google.golang.org/grpc.(*Server).handleStream(0x7fc058239500, {0x7fc04204b2f0, 0x7fc058135520}, 0x7fc05827b320, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b fp=0x7fc0580f7f68 sp=0x7fc0580f7e48 pc=0x7fc041d0207b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98 fp=0x7fc0580f7fe0 sp=0x7fc0580f7f68 pc=0x7fc041cfb5b8
runtime.goexit()
	/opt/ego/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0x7fc0580f7fe8 sp=0x7fc0580f7fe0 pc=0x7fc0416b8d61
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

goroutine 1 [chan receive, 137 minutes]:
github.com/obscuronet/obscuro-playground/go/obscuronode/enclave/enclaverunner.handleInterrupt(0x7fc05803b500)
	/obscuro-playground/go/obscuronode/enclave/enclaverunner/enclave_runner.go:57 +0x91
github.com/obscuronet/obscuro-playground/go/obscuronode/enclave/enclaverunner.RunEnclave({0x2, {0x7fc042850890, 0x6}, {0x7fc041eae3b8, 0x0}, 0x0, {0x7fc041d4dd94, 0x10}})
	/obscuro-playground/go/obscuronode/enclave/enclaverunner/enclave_runner.go:33 +0x1fc
main.main()
	/obscuro-playground/go/obscuronode/enclave/main/main.go:12 +0xe5

goroutine 21 [chan receive, 137 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/core/tx_cacher.go:63 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/core/tx_cacher.go:55 +0x75

goroutine 22 [chan receive, 137 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/core/tx_cacher.go:63 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/core/tx_cacher.go:55 +0x75

goroutine 23 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x7fc0424fa4e0)
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/metrics/meter.go:290 +0x65
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/metrics/meter.go:71 +0xc5

goroutine 24 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0x7fc0580fab40)
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/consensus/ethash/sealer.go:279 +0x205
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/consensus/ethash/sealer.go:263 +0x319

goroutine 27 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0x7fc05808b180, 0x1)
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0x7fc05807f980)
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.NewServerTransport.func2()
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_server.go:326 +0xc6
created by google.golang.org/grpc/internal/transport.NewServerTransport
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_server.go:323 +0x1833

goroutine 28 [select, 18 minutes]:
google.golang.org/grpc/internal/transport.(*http2Server).keepalive(0x7fc058135520)
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_server.go:1125 +0x233
created by google.golang.org/grpc/internal/transport.NewServerTransport
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_server.go:335 +0x1878

goroutine 7 [IO wait, 137 minutes]:
internal/poll.runtime_pollWait(0x7fc055e471b8, 0x72)
	/opt/ego/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x7fc058216400?, 0x7fc05803e500?, 0x0)
	/opt/ego/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/ego/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0x7fc058216400)
	/opt/ego/go/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0x7fc058216400)
	/opt/ego/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0x7fc05800e648)
	/opt/ego/go/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0x7fc05800e648)
	/opt/ego/go/src/net/tcpsock.go:288 +0x3d
google.golang.org/grpc.(*Server).Serve(0x7fc058239500, {0x7fc042047948, 0x7fc05800e648})
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:779 +0x362
github.com/obscuronet/obscuro-playground/go/obscuronode/enclave.StartServer.func1({0x7fc042047948, 0x7fc05800e648})
	/obscuro-playground/go/obscuronode/enclave/server.go:53 +0x9d
created by github.com/obscuronet/obscuro-playground/go/obscuronode/enclave.StartServer
	/obscuro-playground/go/obscuronode/enclave/server.go:51 +0x371

goroutine 9 [syscall, 137 minutes]:
os/signal.signal_recv()
	/opt/ego/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	/opt/ego/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/opt/ego/go/src/os/signal/signal.go:151 +0x2a

goroutine 29 [runnable]:
syscall.Syscall(0x0, 0x8, 0x7fc0581f4000, 0x8000)
	/opt/ego/go/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.read(0x7fc0580fcc00?, {0x7fc0581f4000?, 0x1007fc041eae400?, 0x7fc041664725?})
	/opt/ego/go/src/syscall/zsyscall_linux_amd64.go:696 +0x4d
syscall.Read(...)
	/opt/ego/go/src/syscall/syscall_unix.go:188
internal/poll.ignoringEINTRIO(...)
	/opt/ego/go/src/internal/poll/fd_unix.go:794
internal/poll.(*FD).Read(0x7fc0580fcc00?, {0x7fc0581f4000?, 0x8000?, 0x8000?})
	/opt/ego/go/src/internal/poll/fd_unix.go:163 +0x285
net.(*netFD).Read(0x7fc0580fcc00, {0x7fc0581f4000?, 0x7fc04285f108?, 0x18?})
	/opt/ego/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0x7fc0580ac740, {0x7fc0581f4000?, 0x7fc041f9b340?, 0x2758010001?})
	/opt/ego/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0x7fc058088cc0, {0x7fc05811e2e0, 0x9, 0x7fc058914be8?})
	/opt/ego/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x7fc042042068, 0x7fc058088cc0}, {0x7fc05811e2e0, 0x9, 0x9}, 0x9)
	/opt/ego/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/opt/ego/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0x7fc05811e2e0?, 0x9?, 0x7fc058082080?}, {0x7fc042042068?, 0x7fc058088cc0?})
	/root/go/pkg/mod/golang.org/x/net@v0.0.0-20211216030914-fe4d6282115f/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0x7fc05811e2a0)
	/root/go/pkg/mod/golang.org/x/net@v0.0.0-20211216030914-fe4d6282115f/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0x7fc058135520, 0x0?, 0x0?)
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_server.go:605 +0xb2
google.golang.org/grpc.(*Server).serveStreams(0x7fc058239500, {0x7fc04204b2f0?, 0x7fc058135520})
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:905 +0x142
google.golang.org/grpc.(*Server).handleRawConn.func1()
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:847 +0x46
created by google.golang.org/grpc.(*Server).handleRawConn
	/root/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:846 +0x185
```

**Comment by GavT** [comment]
Nodes ran for 11 hours last night. Closing this bug.
